name: "MACSio"
author: "Elsa Gonsiorowski <gonsiorowski1@llnl.gov>"
description: "Muli-purpose, Application-Centric, Scalable I/O Proxy Application"

githubrepo: MACSio
baseurl: /MACSio

permalink: pretty
